language: python

python:
- 3.5

env:
- DJANGO=1.11.5

install:
- pip install -r requirements.txt
- pip install codeclimate-test-reporter
- pip install -q Django==$DJANGO
- pip install flake8 coverage coveralls

script:
- coverage run --source=habitica_slack manage.py test
- flake8 --max-line-length=100 --max-complexity=10 --statistics --benchmark django_slowtests
- coverage report
- coverage run manage.py test

after_script:
- codeclimate-test-reporter --file .coverage # send test coverage report to code climate

after_success: 
- coverage report

after_success: coveralls
